platform:ios,'14.1'
use_frameworks!

target 'TonyHelp' do

    #layout 布局
    pod 'SnapKit'
    #解析库
    # pod 'HandyJSON'
    #网络库
    # pod 'Alamofire'
    #本地数据库
#    pod 'RealmSwift'
    #下拉加载刷新库
    pod 'MJRefresh'
    #图片库
    # pod 'Kingfisher'
    # toast
#    pod 'Toast-Swift'
    #输入框特效三方库
    pod 'TextFieldEffects'
    #键盘管理
    pod 'IQKeyboardManagerSwift'
    #菊花
    pod 'SVProgressHUD'
    # toast
    pod 'Toaster'

end
